sudo: required
language: java
jdk: openjdk8

services:
  - docker
  
env:
  global: 
  - secure: "encrypted-heroku-api-key"
  - COMMIT=${TRAVIS_COMMIT::7}
  
      
before_install:
  - chmod +x mvnw
 
script: 
  - ./mvnw clean install -B
  
cache:
  directories:
    - '$HOME/.m2/repository'
  
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=crisda24/herokudemo
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: heroku-demo-cris